# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-19 09:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=100, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u5bb9\u5668\u540d')),
                ('imagename', models.CharField(db_column='image_name', max_length=20, verbose_name='\u6240\u5c5e\u955c\u50cf')),
                ('imageid', models.CharField(db_column='image_id', max_length=100, verbose_name='\u6240\u5c5e\u955c\u50cfID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('state', models.CharField(max_length=10, verbose_name='\u72b6\u6001')),
            ],
            options={
                'verbose_name': '\u5bb9\u5668\u5217\u8868',
                'verbose_name_plural': '\u5bb9\u5668\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(protocol='ipv4', unique=True, verbose_name='IP\u5730\u5740')),
                ('container_number', models.IntegerField(verbose_name='\u5bb9\u5668\u6570\u91cf')),
                ('image_number', models.IntegerField(verbose_name='\u955c\u50cf\u6570\u91cf')),
                ('info', models.TextField(verbose_name='\u5bbf\u4e3b\u673a\u72b6\u6001')),
            ],
            options={
                'verbose_name': '\u5bbf\u4e3b\u673a\u5217\u8868',
                'verbose_name_plural': '\u5bbf\u4e3b\u673a\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=100, unique=True, verbose_name='ID')),
                ('repository', models.CharField(max_length=50, unique=True, verbose_name='\u4ed3\u5e93\u955c\u50cf')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('container_number', models.IntegerField(verbose_name='\u5bb9\u5668\u6570\u91cf')),
                ('size', models.CharField(max_length=100, verbose_name='\u955c\u50cf\u5927\u5c0f')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Host', to_field='ip', verbose_name='\u6240\u5c5e\u5bbf\u4e3b\u673a')),
            ],
            options={
                'verbose_name': '\u955c\u50cf\u5217\u8868',
                'verbose_name_plural': '\u955c\u50cf\u5217\u8868',
            },
        ),
        migrations.AddField(
            model_name='container',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Host', to_field='ip', verbose_name='\u6240\u5c5e\u5bbf\u4e3b\u673a'),
        ),
    ]
