# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-27 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='repository',
            field=models.CharField(max_length=50, verbose_name='\u4ed3\u5e93\u955c\u50cf'),
        ),
    ]
